### ISSUE TITLE
CallLogRecordLegInfo missing "reason" field

### ISSUE THREAD

**Issue by dougkpowers** [ringcentral/RingCentral.Net#11]
The CallLogRecordLegInfo class should delcare a "reason" field per the Swagger doc:

https://netstorage.ringcentral.com/dpw/api-reference/specs/rc-platform.yml?v=2019032720190322-1152

**Comment by tylerlong** [comment]
Hi @dougkpowers from the link you posted, I see that CallLogRecordLegInfo class does NOT have a reason field. Could you please double check?

**Comment by dougkpowers** [comment]
you're right....but it's there in the payload that gets returned from the api call.

I wonder why it's in the payload but not documented in the swagger doc?

**Comment by tylerlong** [comment]
@dougkpowers Then it is a bug of our swagger spec. I will escalate this issue.

Once swagger spec fixed, I will release new version of the SDK.

**Comment by tylerlong** [comment]
Fixed
