### ISSUE TITLE
Fax cover page info

### ISSUE THREAD

**Issue by drinkwater99** [ringcentral/RingCentral.Net#12]
Based on the following post, when sending a fax, it seems to be possible to add a "name" value in addition to the "to" phone number which will appear in the fax cover page.

https://forums.developers.ringcentral.com/idea/225/fax-cover-info.html

I dont see any parameters in the CreateFaxMessageRequest or in MessageStoreCallerInfoRequest to specify the "name" value.

Is this supposed to be supported in he sdk or is there another way to do it ?

**Comment by tylerlong** [comment]
Supported in version . 2.3.0
