### ISSUE TITLE
GetRingOutStatusResponse ID was updated to an incorrect type

### ISSUE THREAD

**Issue by hvdrew** [ringcentral/RingCentral.Net#13]
It looks like in a recent commit the `id` property of `GetRingOutStatusResponse` was updated from a `string` to a `long` type. This causes an error to be thrown when using the RingOut API. Discovered this issue after following your getting started guide for C#.

https://github.com/ringcentral/RingCentral.Net/blob/552a53fb5bfe3a198e8abe70648e2180544895c7/RingCentral.Net/Definitions/GetRingOutStatusResponse.cs#L8

**Comment by tylerlong** [comment]
Confirmed. The code was generated based on swagger spec. I will notice the spec maintainer to fix the spec first, then regenerate the code.

**Comment by tylerlong** [comment]
In latest version the ID is string.
