### ISSUE TITLE
API limit information is not exposed

### ISSUE THREAD

**Issue by BryceBarbara** [ringcentral/RingCentral.Net#17]
Most valid responses from the API return with headers which contain useful information about the current state of API limits.

Without this info, it makes it very difficult to anticipate `429 Too Many Request` errors if two competing systems are using the same user account through the API.

**Comment by tylerlong** [comment]
Most of users don't need headers information. So this SDK by default doesn't return it.

For those who need headers, try this: https://github.com/ringcentral/RingCentral.Net/blob/master/RingCentral.Tests/LowLevelApiTest.cs#L59-L70

**Comment by tylerlong** [comment]
I've added doc: https://github.com/ringcentral/RingCentral.Net#how-to-access-headers

**Comment by BryceBarbara** [comment]
Thanks for the quick response Tyler!

Although I agree that _technically_ we can access the headers if we handle all response processing ourselves, I feel like the point of the SDK is being missed if that's truly the solution. 

Not only does it mean that there will be different implementations for each project, it also removes half of the SDK's value since it would only be used to prepare the requests at that point.

It's almost as if a car didn't have a fuel gauge and instead of adding one, the car manufacturer suggested that users just make their own engine for the car that supports fuel gauges.

**Comment by BryceBarbara** [comment]
And just to touch on your point about most users not needing the headers, with API limits as low as RingCentral's, I'd have to disagree. 

If the info is important enough for every response to contain it, it seems like it should be important enough to officially support.

**Comment by tylerlong** [comment]
Are you suggesting something like this:

```cs
var r = await rc.Restapi().Account("~").Extension("~").Get();
var headers = r.headers
var extInfo = r.body
```

?

**Comment by BryceBarbara** [comment]
Exposing the raw headers isn't ideal since we'd still need parse them manually.

I was imagining some sort of property named something like `ApiLimits` that all the response objects have. That `ApiLimits` object would look something like this:

```c#
struct ApiLimitsInformation {
  public string LimitGroup { get; set; }
  public TimeSpan LimitWindow { get; set; }
  public int TotalLimit { get; set; }
  public int RemainingCalls { get; set; }
}
```

Let me know if that doesn't make sense. I'm happy to clarify in some other way if needed!

**Comment by tylerlong** [comment]
There is another way, not sure you like it. https://github.com/ringcentral/RingCentral.Net/blob/master/RingCentral.Tests/AfterCallTest.cs

It's listener pattern so for each http call you can get headers.

**Comment by BryceBarbara** [comment]
It still requires us to parse the headers ourselves and it's also not idomatic C#.

Here's an boiled down example of why I think it's important to give access to it via the response objects.

```cs
var listOfCallIds = this.getSomeArrayFullOfTelephonyIds();
var responses = new List<SomeType>();

foreach (var callId in listOfCallIds) {
  var response = await this._rc.Restapi().Account("~").Extension("~").CallLog(callId).Get();
  responses.Add(response);

  if (response.ApiLimits.RemainingCalls < 1) {
    // Wait some time to avoid getting rate limited
    await Task.Delay(1000 * 61);
  } 
}
```

**Comment by tylerlong** [comment]
The overall idea is good. But I don't like the idea of adding `ApiLimitsInformation` to the response object. Because that information doesn't belong to the object. And the information is temporary only.  `RemainingCalls` only makes sense at that moment, it will become out-of-date very soon.

**Comment by tylerlong** [comment]
> It still requires us to parse the headers ourselves and it's also not idomatic C#.

Yes it does. But you can handle it in a central place (in the event handler) instead of modify code every where.

It is idomatic C#. Check this: [C# events](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/events/how-to-subscribe-to-and-unsubscribe-from-events).

I am not saying it's the best solution for you. It's just an option FYI.

**Comment by tylerlong** [comment]
Some code snippets currently in my mind:

```cs
var rateLimitTracking = new Dictionary<string, int>{
{ 'Light', 10 }
{ 'Medium', 10 }
{ 'Heavy', 10 }
{ 'Auth', 10 }
}
void EventHandler(object sender, HttpCallEventArgs eventArgs)
{
   var rateLimitGroup = eventArgs.httpResponseMessage.Headers
        .First(i => i.Key == "X-Rate-Limit-Group").Value.First();
   var rateLimitRemaining =int.Parse(eventArgs.httpResponseMessage.Headers
        .First(i => i.Key == "X-Rate-Limit-Remaining").Value.First());
    rateLimitTracking[rateLimitGroup] = rateLimitRemaining
}
rc.AfterHttpCall += EventHandler;


var listOfCallIds = this.getSomeArrayFullOfTelephonyIds();
var callLogs = new List<CallLogInfo>();
foreach (var callId in listOfCallIds) {
  var callLog = await rc.Restapi().Account("~").Extension("~").CallLog(callId).Get();
  responses.Add(callLog);
  if (rateLimitTracking["Heavy"] < 1) {
    // Wait some time to avoid getting rate limited
    await Task.Delay(1000 * 61);
  } 
}
```

**Comment by tylerlong** [comment]
I can add an experimental feature. Add `rateLimitTracking` to `RestClient`. So that as end user you don't need to parse headers.

**Comment by tylerlong** [comment]
New feature added in 4.0.0-beta3

Usage: https://github.com/ringcentral/RingCentral.Net/blob/master/RingCentral.Tests/RateLimitsTest.cs

**Comment by tylerlong** [comment]
New users should use the [Rate Limit Extension](https://github.com/ringcentral/RingCentral.Net/tree/master/RingCentral.Net.RateLimit)
