### ISSUE TITLE
Add support for CancellationTokens

### ISSUE THREAD

**Issue by BryceBarbara** [ringcentral/RingCentral.Net#18]
Without support for CancellationTokens, we're unable to stop pending requests or properly implement timeouts without resorting to either killing threads or orphaning tasks.

After doing a quick poke around, it looks like initial support could be added by allowing for the passing of an optional CancellationToken to the SendAsync call at [RestClient.cs:55](https://github.com/ringcentral/RingCentral.Net/blob/master/RingCentral.Net/RestClient.cs#L55) and then updating all the functions that call into this `Request()` function.

**Comment by tylerlong** [comment]
The underlying HTTP library is `System.Net.Http;`

Could you please show me some sample code using `System.Net.Http`? Not sure how to do it. Thanks.

**Comment by tylerlong** [comment]
Supported in 4.0.0-beta2

**Comment by BryceBarbara** [comment]
Great work Tyler! Thanks for the quick turn-around on this. It's something that definitely makes the SDK feel a bit more ready for prime-time usage!
