### ISSUE TITLE
Passing a token when using the CallOut endpoint

### ISSUE THREAD

**Issue by GenEqDev** [ringcentral/RingCentral.Net#19]
Hello,

We are having trouble finding information on how to pass a token when using the CallOut endpoint. Could we get some direction on how to do that, or at least directed to documentation that covers that issue?

Thank you!

**Comment by tylerlong** [comment]
Hi, next time please send email to devsupport@ringcentral.com
GitHub is only for reporting issues about the SDK itself, not for questions.

For `pass a token`, I assume you already have a token somewhere? Here is how you can set a token: https://github.com/ringcentral/RingCentral.Net/blob/master/RingCentral.Tests/AuthorizationTest.cs#L159

```cs
var rc = new RestClient("clientID", "clientSecret", "serverURL"));
rc.token = token; // I assume you have `token` already
var result = await rc.Restapi(apiVersion).Account(accountId).Telephony().CallOut().Post(makeCallOutRequest);
```
