### ISSUE TITLE
sample code title case issue

### ISSUE THREAD

**Issue by tylerlong** [ringcentral/RingCentral.Net#2]
`Create ivr menu` should be `Create IVR Menu`

Be consistent with https://developer.ringcentral.com/api-reference

**Comment by grokify** [comment]
Here's what the menu names look like in the API Reference. It would be good for these to be consistent.

<img width="692" alt="screen shot 2019-03-07 at 7 10 02 pm" src="https://user-images.githubusercontent.com/209872/54005029-b98dc600-410c-11e9-8ae3-f2b840437e24.png">

**Comment by tylerlong** [comment]
Fixed
