### ISSUE TITLE
Object Reference

### ISSUE THREAD

**Issue by TonyValenti** [ringcentral/RingCentral.Net#20]
I'm getting an object reference error trying to authenticate:

```
var Api = new RingCentral.RestClient(ClientId, ClientSecret);

                var AuthUri = Api.AuthorizeUri(new AuthorizeRequest() {
                    response_type = "code",
                    client_id = ClientId,
                    redirect_uri = RedirectUri
                });
//Launch the AuthUri and get the Code
...

//This throws an object reference error:
                var Token = await Api.Restapi().Oauth().Token().Post(new GetTokenRequest() {
                    grant_type = "authorization_code",
                    code = Code,
                    redirect_uri = RedirectUri,
                });

```

What should I do differently?

**Comment by tylerlong** [comment]
Please post the full stack trace. `object reference error`, which object does it mean?   
Is it `Api`? Maybe you didn't initialize it before using it.
You did initialize it in your first line of the code snippet above. But I am not sure that the last line of your code is in the same scope of your first line.  
Overall this is just C# programming issue.
Feel free to re-open if you think it is an issue of this SDK.
