### ISSUE TITLE
Api.Restapi().Account().Presence().Put() Does not Exist

### ISSUE THREAD

**Issue by TonyValenti** [ringcentral/RingCentral.Net#21]
The docs at this link say it should:
https://github.com/ringcentral/RingCentral.Net/blob/master/samples.md

**Comment by tylerlong** [comment]
No, the docs don't say it should.

The docs only mentioned **GET** `/restapi/v1.0/account/{accountId}/presence`

There is no **PUT** `/restapi/v1.0/account/{accountId}/presence`.

Feel free to re-open it if you have questions regarding this.

**Comment by tylerlong** [comment]
The doc do say that **PUT** `/restapi/v1.0/account/{accountId}/extension/{extensionId}/presence` is supported.

You should try `Api.Restapi().Account().Extension().Presence().Put()` instead of `Api.Restapi().Account().Presence().Put()`
