### ISSUE TITLE
Debugger Display

### ISSUE THREAD

**Issue by TonyValenti** [ringcentral/RingCentral.Net#24]
Hi @tylerlong 
Can you please annotate the various classes with the ```[DebuggerDisplayAttribute]```?  This will make inspecting them in the Visual Studio much easier.
Here's example code:
````
using System;
using System.Diagnostics;

namespace ConsoleApp58 {
    class Program {
        static void Main(string[] args) {
            var MyExample = new Example() {
                UserName = "User@User.com",
                Password = "P@$$w0rd"
            };
        }
    }

    public class Example : RcObject {
        public string UserName { get; set; }
        public string Password { get; set; }

        protected override string GetDebuggerDisplay() {
            return $@"{UserName}: {Password}";
        }

    }



    [DebuggerDisplay("{GetDebuggerDisplay(),nq}")]
    public abstract class RcObject {
        protected abstract string GetDebuggerDisplay();
    }

}
````
And this makes it so that when you mouse-over a variable of that type, you get a nice UI:
![image](https://user-images.githubusercontent.com/13609558/91172915-978e5780-e6a2-11ea-9c98-ba982deefa5d.png)

**Comment by tylerlong** [comment]
Thanks for the suggestions. This is kind of new to me.

What is `nq` in `[DebuggerDisplay("{GetDebuggerDisplay(),nq}")]`?

**Comment by tylerlong** [comment]
I guess without [DebuggerDisplayAttribute], you can still inspect the variable in local variables window. It's just the "hover and show" feature is missing.

**Comment by TonyValenti** [comment]
The ```nq``` means "don't show quotes around the value."

In the screen shot, if it did not have nq, it would show the value as  ```"User@User.com: P@$$w0rd"``` instead of ```User@User.com: P@$$w0rd```

**Comment by tylerlong** [comment]
Overall this is nice-to-have feature but not essentials.  We won't implement this because classes in this project doesn't have a ready to be used `GetDebuggerDisplay()` method. 

As a workaround, you can always inspect the data using local variables debugging window.
