### ISSUE TITLE
Automatically Respect Rate Limits

### ISSUE THREAD

**Issue by TonyValenti** [ringcentral/RingCentral.Net#26]
The API should automatically respect rate limits and if a rate limit exception occurs, it should automatically wait the necessary amount of time.

**Comment by tylerlong** [comment]
By default, there is no "magic" logic enabled.

You can explicitly handle it:

- https://github.com/ringcentral/RingCentral.Net#api-calls-auto-retry
- https://github.com/ringcentral/RingCentral.Net/blob/master/RingCentral.Tests/RateLimitsTest.cs

**Comment by tylerlong** [comment]
The next major version will probably copy the extensions architecture here: https://github.com/ringcentral/ringcentral-extensible/tree/master/packages/extensions
So the core SDK does very core thing. You can have extra features by installing extensions.

**Comment by tylerlong** [comment]
Since version 5.0.0-beta1, there is an extension to handle rate limit: https://github.com/ringcentral/RingCentral.Net/tree/master/RingCentral.Net.RateLimit
