### ISSUE TITLE
Make RestClient members virtual

### ISSUE THREAD

**Issue by TonyValenti** [ringcentral/RingCentral.Net#27]
Hi RingCentral,
Would you please make the members of RestClient virtual?

We would like to override them with custom implementations, specifically to help with token management.

**Comment by tylerlong** [comment]
Could you please specify which members?

As mentioned here https://github.com/ringcentral/RingCentral.Net/issues/26#issuecomment-694341340 we are migrating to an extension architecture in next major version. So inherit and override may not be the way we recommend.

**Comment by tylerlong** [comment]
Since 5.0.0-beta1, this project has been migrated to an extension based architecture.
So if you want to extend the SDK, create an extension. There are already a couple of extensions FYI: https://github.com/ringcentral/RingCentral.Net#extensions
