### ISSUE TITLE
Teams Index List Method PageToken Failure

### ISSUE THREAD

**Issue by soshimozi** [ringcentral/RingCentral.Net#28]
I noticed that the List method on the Teams Index never returns a NextPage token.  It does return a PreviousPage token, but using that results in a failure indicating the pageToken parameter is invalid.  I know there are more than 250 teams and this code works in the javascript library.

Example Code:

            var auth = new RingCentralAuth
            {
                AppSecret = RingCentralAppSecret,
                AppKey = RingCentralAppKey,
                PlatformUrl = RingCentralPlatformUrl,
                UserExtension = extension,
                UserPassword = password,
                UserName = userName,
            });

            _client = new RestClient(auth.AppKey, auth.AppSecret, auth.PlatformUrl);
            _client.Authorize(auth.UserName, auth.UserExtension, auth.UserPassword).Wait();

            var navigation = new GlipNavigationInfo();
            do
            {
                // I can use prevPageToken here with same result
                var queryParameters = new ListGlipTeamsParameters { recordCount = pageSize, pageToken = navigation.nextPageToken };  

                var teams = _client.Restapi().Glip().Teams().List(queryParameters).Result;
                foreach (var team in teams.records)
                {
                    yield return team;
                }

                navigation = teams.navigation;

            } while (navigation.nextPageToken != null);  // I can use prevPageToken here with same result

This same code works using the javascript library - I ported it directly from a javascript function that is working in production today.

**Comment by tylerlong** [comment]
> never returns a NextPage token
Do you mean the value is always null?

**Comment by tylerlong** [comment]
For quicker response, you can send email to devsupport@ringcentral.com.

**Comment by soshimozi** [comment]
I actually got it to work, but it's a bit of a kludgy hack.  I was looking at the code that one of your RC developers wrote for us on a contract and basically replicated that.  The code below is what is working for me:

```
        public async IAsyncEnumerable<GlipGroupInfo> GetTeams(long? pageSize = null)
        {
            var navigation = new GlipNavigationInfo();

            var uri = _client.Restapi().Glip().Groups().Path(false);
            do
            {
                var queryParameters = new { recordCount = pageSize ?? 30, type = new[] { "Team" }, pageToken = navigation.prevPageToken };

                var result = await _client.Get(uri, queryParameters);
                var contentString = await result.Content.ReadAsStringAsync();

                var groups = Newtonsoft.Json.JsonConvert.DeserializeObject<GlipGroupResponse>(contentString);

                foreach (var team in groups.Records)
                {
                    yield return team;
                }

                navigation = groups.Navigation;

            } while (navigation.prevPageToken != null);
        }
```

**Comment by tylerlong** [comment]
Do you have a RingCentral app installed? You can ping me to have a live chat. My email is tyler.liu@ringcentral.com
I appreciate your feedbacks to this SDK.

**Comment by soshimozi** [comment]
This seems to be an issue with the API and not related to the SDK.  I'm going to close this issue.  Thank you Tyler for looking into this!

**Comment by tylerlong** [comment]
Thanks for the update!

Below is just a small trick:

I think 

```cs
var result = await _client.Get(uri, queryParameters);
var contentString = await result.Content.ReadAsStringAsync();
var groups = Newtonsoft.Json.JsonConvert.DeserializeObject<GlipGroupResponse>(contentString);
```

could be simplified to

```cs
var groups = await _client.Get<GlipGroupResponse>(uri, queryParameters);
```
