### ISSUE TITLE
NullReference when revoking a subscription that wasn't Subscribed

### ISSUE THREAD

**Issue by BryceBarbara** [ringcentral/RingCentral.Net#29]
As the title says, you can't currently cancel a subscription when you have the `SubscriptionInfo` object for it although it seems like you should.

Here's some example code explaining the scenario I'm trying to do:
```c#
var subscriptionInfos = await GetActiveSubscriptionsWeDontNeed();
foreach (var subInfo in subscriptionInfos) {
  var sub = new Subscription(_rc, subInfo.eventFilters, OnSubscriptionMessage) {
    subscriptionInfo = subInfo
  };
  await sub.Revoke();
}
```

Although I'm not positive, it looks like this might be the problem line:
https://github.com/ringcentral/RingCentral.Net/blob/7635cc8e4d34639dab4751f9ddc333f1d47a86cd/RingCentral.Net.PubnubPCL/Subscription.cs#L115

**Comment by tylerlong** [comment]
If you never `Subscribe`, you don't have to call `Revoke`. You just de-reference it and it will be garbage collected by .NET runtime.

You can see that the constructor doesn't consume any system/network resource: https://github.com/ringcentral/RingCentral.Net/blob/7635cc8e4d34639dab4751f9ddc333f1d47a86cd/RingCentral.Net.PubnubPCL/Subscription.cs#L45-L57. So there is nothing to revoke.

**Comment by BryceBarbara** [comment]
I'm trying to cancel a subscription that was started in another instance that fatally exited. I've found that if I don't cancel it in advance, I get duplicate notifications. 

There's currently no way to do cancel the orphaned subscriptions with the system as it stands.

**Comment by tylerlong** [comment]
> I'm trying to cancel a subscription that was started in another instance that fatally exited.

What do you mean by "fatally exited"? And what is "another instance"? Do you mean another process or another object?

> There's currently no way to cancel the orphaned subscriptions with the system as it stands.

There is, as long as you have the subscription ID. You just invoke this https://github.com/ringcentral/RingCentral.Net/blob/7635cc8e4d34639dab4751f9ddc333f1d47a86cd/RingCentral.Net.PubnubPCL/Subscription.cs#L101

**Comment by tylerlong** [comment]
In latest version, code has been changed t `_pubnub?.Revoke()` which will not throw if `_pubnub` is null.
