### ISSUE TITLE
Update comment style

### ISSUE THREAD

**Issue by tylerlong** [ringcentral/RingCentral.Net#3]
![image](https://user-images.githubusercontent.com/733544/54899576-2bd31880-4f0b-11e9-8647-999c87b9fb8f.png)

**Comment by RukaiYu** [comment]
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/recommended-tags-for-documentation-comments full list of the DOC

**Comment by tylerlong** [comment]
Done
