### ISSUE TITLE
Deserializing GlipGroupsEvent will result in an error for current Glip Webhooks implementation.

### ISSUE THREAD

**Issue by agreentejada** [ringcentral/RingCentral.Net#31]
This is the body of a GroupJoined event from using the Glip endpoints for RingCentral.

` "body": {
        "id": "11111111",
        "name": "Test Team",
        "description": null
        "type": "Team",
        "status": "Active",
        "members": [
            "287828004"
        ],
        "isPublic": true,
        "creationTime": "2021-01-23T04:06:05.366Z",
        "lastModifiedTime": "2021-01-23T04:06:05.366Z",
        "eventType": "GroupJoined"
    }`

Note that "members" is an array of strings. However, in RingCentral.Net, "members" is an array of GlipMemberInfo, which only has a single string property. This causes a deserialization error if deserializing from JSON.NET. Please fix the object's implementation.

**Comment by tylerlong** [comment]
@agreentejada which class are you talking about?
https://github.com/ringcentral/RingCentral.Net/blob/e6f383d7d2304ee61659cbe17337fdccee5b37ab/RingCentral.Net/Definitions/GlipGroupsEvent.cs#L34

**Comment by tylerlong** [comment]
I think the issue doesn't exist any more. Feel free to re-open this issue. Thanks.
