### ISSUE TITLE
Access Tokens get revoked when RestClient is disposed preventing future use

### ISSUE THREAD

**Issue by ahawes-clarity** [ringcentral/RingCentral.Net#37]
I need to use the recommended 3-legged Auth Code Flow.

I am using RingCentral.Net and the Authorize method with a GetTokenRequest passing in the Authorization Code and Redirect Uri.

I get back an Access Token (TokenInfo object) and I store it for later use.

However, when I go to use it later, 99% of the time the request fails because the Token is not found or said to be corrupt.

When I was looking at the SDK code today I noticed that when the RestClient is disposed it seems to call the Revoke method which seems to call the oauth/revoke endpoint of the RingCentral API. This would seem to have the affect of revoking the token.

Is this the case?

How can I use a stored Access Token if the RestClient will always revoke the token?

![image](https://user-images.githubusercontent.com/6013584/131873852-a53eeb70-ac66-499e-bcec-e5bf74aa12c0.png)

**Comment by tylerlong** [comment]
I have updated the docs: https://github.com/ringcentral/RingCentral.Net#c-using-statement

In short, do not use `using` if you want to retain the token.
