### ISSUE TITLE
What permissions are required to use the Extension Telephony Sessions Event (Beta) notification?

### ISSUE THREAD

**Issue by tsf1** [ringcentral/RingCentral.Net#4]
Trying to hook up notifications for /restapi/v1.0/account/~/telephony/sessions and keep getting an error that says "Required application permission [TelephonySessions] is missing." However, I don't see that permission option under OAuth settings. I've added every option there to see if something else works but can't get around this. I'm calling v1.0.38.

**Comment by tylerlong** [comment]
This permission is in beta and I am afraid that it is not publicly available. Please contact devsupport@ringcentral.com and they will help.
