### ISSUE TITLE
ListDirectoryEntriesParameters doesn't accept "max" or "all" for per page parameter.

### ISSUE THREAD

**Issue by jnamey** [ringcentral/RingCentral.Net#41]
https://developers.ringcentral.com/api-reference/Internal-Contacts/listDirectoryEntries

Says that perPage accepts "all" or "max" as values for pages.

**Comment by tylerlong** [comment]
It is a known issue. Since the field is an integer, C# doesn't all string values.

**Comment by tylerlong** [comment]
I have created an internal ticket to change the data type of the API spec.

**Comment by tylerlong** [comment]
Issue resolved. perPage is a string now.
