### ISSUE TITLE
How do I refresh token?

### ISSUE THREAD

**Issue by ullfindsmit** [ringcentral/RingCentral.Net#43]
Currently I get OAuth token back on my first call.
However, that token expires and I am trying to figure out how to refresh/extend it.

There is no refresh token method listed here
https://github.com/ringcentral/RingCentral.Net/blob/14fcf40c56ba53f0db4fed5d180dab9fb79bce15/samples.md

And https://developers.ringcentral.com/guide/authentication/refresh-tokens talks about refresh, but I'm not sure where the refresh_token value comes from.

Help appreciated.

**Comment by tylerlong** [comment]
Sorry for the late reply. But here is not the best way to get help.  You should have created a support ticket here https://developers.ringcentral.com/

**Comment by tylerlong** [comment]
For your question, it is as simple as `await rc.Refresh()`;
