### ISSUE TITLE
ExtensionTelephonySessionsEvent removed

### ISSUE THREAD

**Issue by agaskill** [ringcentral/RingCentral.Net#47]
In commit fdda6bc8a00f8cd02f4f775bf70ff63cff2971b8 ExtensionTelephonySessionsEvent and related classes were removed.

**Comment by tylerlong** [comment]
Yes, I confirm this issue. For some reason that class (and a few other classes) disappeared from our spec. I have escalated the issue.

**Comment by tylerlong** [comment]
https://github.com/ringcentral/RingCentral.Net/blob/master/RingCentral.Net/Definitions/ExtensionTelephonySessionsEvent.cs

It's back.
