### ISSUE TITLE
RingCentral.NET 5.18.0 - class NotificationDeliveryModeRequest not found

### ISSUE THREAD

**Issue by gsandorx** [ringcentral/RingCentral.Net#48]
After upgrading to version 5.18.0, this class is no longer found in the RingCentral namespace. Up to 5.17.0, everything was working fine.

I couldn't find any "migration" guide referencing the replacement type.

Any ideas?

**Comment by tylerlong** [comment]
I believe it has been renamed to NotificationDeliveryMode
Ref: https://github.com/ringcentral/RingCentral.Net/blob/master/RingCentral.Net/Definitions/CreateSubscriptionRequest.cs#L14

Sorry for the breaking change. 99% of the code was auto generated based on API specs. So upstream renaming of the models will cause breaking changes in this project.
