### ISSUE TITLE
Error in CompanyAnsweringRuleRequest

### ISSUE THREAD

**Issue by mediocreguy** [ringcentral/RingCentral.Net#55]
class CompanyAnsweringRuleRequest

extension property should be type CompanyAnsweringRuleExtensionInfoRequest  not CompanyAnsweringRuleCallersInfoRequest

JIMB

**Comment by tylerlong** [comment]
The code is auto generated based on API spec.

I will talk to the maintainer of the API spec.

**Comment by tylerlong** [comment]
Confirmed the issue, I created an internal ticket to track it.

**Comment by tylerlong** [comment]
Fixed
