### ISSUE TITLE
Dispose System.Net.HttpClient

### ISSUE THREAD

**Issue by tylerlong** [ringcentral/RingCentral.Net#7]
Make it singleton?

> System.Net.HttpClient, which implements IDisposable, but it is not being disposed.  I'm concerned that this could be creating a memory leak.

> I'd recommend that pattern be implemented in the library.  But also, it might make sense for the developer to be able to provide an instance of HttpClient to the library.  In my case I will already be using one, and could easily provide it when constructing the RingCental object or when calling RestApi().

**Comment by dougkpowers** [comment]
See https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/

**Comment by tylerlong** [comment]
https://docs.microsoft.com/en-us/azure/architecture/antipatterns/improper-instantiation/

**Comment by tylerlong** [comment]
I am working on it now.

**Comment by tylerlong** [comment]
In 2.3.1, httpClient is a static variable. And it is public so you can replace it with your own if you want to.
