### ISSUE TITLE
Using CallLog() return 0

### ISSUE THREAD

**Issue by JLOrdaz** [ringcentral/RingCentral.Net#71]
I am using the SDK and a C# program, and based on the website example, but it never brings up the call details.
Is there anything additional to what the documentation says that I should check? has any of this happened?

**Comment by tylerlong** [comment]
Please create a support ticket here: https://developers.ringcentral.com/support/create-case

By default, the API only returns results for the last 24 hours. If there is no call log for the last 24 hours, you will get 0.
Please create a ticket if your have further questions. I don't think it's a SDK issue, so I will close it for now.
