### ISSUE TITLE
SDK throwing error while deserializing CSN notification event

### ISSUE THREAD

**Issue by vyshakhbabji** [ringcentral/RingCentral.Net#9]
When trying to make a call using the CallSessions approach with the C# SDK, I'm getting an error. The call still goes through, but it looks like the SDK is having some issues parsing the JSON response. The error means that we're unable to process the response as we don't get it. The error is: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'RingCentral.CallParty' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.

To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.
Path 'session.parties', line 8, position 19.

**Comment by tylerlong** [comment]
Can we get more detail please? Such as code snippet?
It doesn't seem like a notification issue:
> When trying to make a call using the CallSessions approach

**Comment by vyshakhbabji** [comment]
// https://developers.ringcentral.com/my-account.html#/applications
// Find your credentials at the above url, set them as environment variables, or enter them below

// PATH PARAMETERS
string accountId = "<ENTER VALUE>";

// POST BODY
MakeCallOutRequest makeCallOutRequest = new MakeCallOutRequest {
    from = new MakeCallOutCallerInfoRequestFrom {
        deviceId = "<ENTER VALUE>"
    },
    to = new MakeCallOutCallerInfoRequestTo {
        phoneNumber = "<ENTER VALUE>",
        extensionNumber = "<ENTER VALUE>"
    }
};

RestClient rc = new RestClient(
    Environment.GetEnvironmentVariable("clientId"),
    Environment.GetEnvironmentVariable("clientSecret"),
    false
);
await rc.Authorize(
    Environment.GetEnvironmentVariable("username"),
    Environment.GetEnvironmentVariable("extension"),
    Environment.GetEnvironmentVariable("password")
);
var r = await rc.Restapi().Account(accountId).Telephony().CallOut().Post(makeCallOutRequest);
// PROCESS RESPONSE

**Comment by vyshakhbabji** [comment]
@tylerlong  u r right , this is with callout api call using c# code snippet on the api explorer

**Comment by tylerlong** [comment]
<img width="573" alt="Screen Shot 2019-09-03 at 3 12 38 PM" src="https://user-images.githubusercontent.com/733544/64212167-4ff13900-ce5d-11e9-8844-d5bb49a25cba.png">

I just tired this endpoint and I had no problem

**Comment by tylerlong** [comment]
Oh, I forgot I just release the latest 2.0.1 version of the SDK. Please have a try and let me know if you still have this issue.
